#! -*-perl-*-

=head1 NAME

_ADD_SKY_LOG_ENTRY_ - Write sky parameters log entry to disk

=head1 SYNOPSIS

  _ADD_SKY_LOG_ENTRY_ DCSKY=25.0 

=head1 DESCRIPTION

Write entry to C<log.sky> with parameters from estimation of sky parameters

=head1 ARGUMENTS

The following arguments are supported

=over 4

=item DCSKY

Mean DC sky level (pW). Mandatory.

=item SKYGRAD

Gradient in sky emission (pW per radian). A default value of 0 is
assumed if not specified.

=item SKYPA

Position angle (in degrees E of N) of gradient in sky emission in AZEL
frame. A default value of 0 is assumed if not specified.

=back

=head1 FORMAT

The logfile has the following columns:

=over 4

=item UT

The UT date in C<YYYYMMDD.frac> format.

=item HST

The time of the observation in Hawaii.

=item Obs

The observation number.

=item Source

The source name.

=item Mode

The observing mode.

=item Filter

The specific filter associated with the fcf result.

=item Elevation

The elevation of the observation.

=item CSO

Equivalent CSO tau derived from the tau used to reduce
the observation.

=item Tau

The tau value used for the reduction.

=item Seeing

The seeing value as stored in the header.

=item DC sky

Mean sky level

=item Sky gradient

Gradient in the sky emission if present

=item Gradient position angle

Position angle of the derived sky emission gradient in the AZEL frame

=head1 FILES

Creates an output log file called C<log.sky>

=head1 AUTHOR

Andy Gibb E<lt>agg@astro.ubc.caE<gt>

Copyright (C) 2008 the University of British Columbia.  All Rights
Reserved.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307,
USA

=cut

# Read arguments
my $dcsky = get_prim_arg( $_PRIM_ARGS_, "DCSKY", undef );
unless (defined $dcsky) {
  orac_throw("ADD_SKY_LOG_ENTRY: DCSKY must be specified as an argument");
}
my $skygrad = get_prim_arg($_PRIM_ARGS_, "SKYGRAD", 0.0);
my $skypa = get_prim_arg($_PRIM_ARGS_, "SKYPA", 0.0);

my $usegroup = get_prim_arg( $_PRIM_ARGS_, "GROUP", 0);

# Create new log file if necessary
my $time = gmtime();
my $skylog = new ORAC::LogFile("log.sky");
$skylog->header("#Sky properties log file - created on $time UT",
		"#\n# UT                HST   Obs Source       Mode           Filter  El CSO    Tau  Seeing  DC_sky       Slope     PA",
		"#---------------------------------------------------------------------------------------------------------------------");


# Obtain common parameters
_GET_LOG_PARAMETERS_ GROUP=$usegroup
my ( $uttime, $hst, $obsnum, $src, $mode, $filter, $el, $cso, $tau, $see ) 
  = @{ $_GET_LOG_PARAMETERS_{PARAMS} };

# Reformat sky parameters for printing
$dcsky = sprintf "%12.7f", $dcsky;
$skygrad = sprintf "%10.7f", $skygrad;
$skypa = sprintf "%4.1f", $skypa;

# Write logfile entry
$skylog->addentry("$uttime $hst $obsnum $src $mode   $filter   $el $cso $tau $see  $dcsky $skygrad $skypa");
