#! -*-perl-*-

=head1 NAME

_MAKE_MOSAIC_FRAME_ - Create frame mosaic

=head1 SYNOPSIS

 _MAKE_MOSAIC_FRAME_ MAKEMOS=1 METHOD=MEAN GENVAR=0

=head1 DESCRIPTION

This primitive is a Frame-specific wrapper to _MAKE_MOSAIC_.

=head1 ARGUMENTS

=over 4

=item B<METHOD>

The method to be used to combine the images.The meaning of this
argument depends on the application used but in principle it could be
any valid value. See MAKEMOS and/or WCSMOSAIC documentation for
further details.

=item B<GENVAR>

Flag to determine whether or not to use genvar when
mosaicking. Default is 1 (yes),

=item B<VERBOSE>

Flag to denote whether to display extra information. Default is 0
(no).

=back

=head1 FILE SUFFIX

Creates a single output image with a suffix of '_fmos'.

=head1 AUTHOR

Andy Gibb E<lt>agg@astro.ubc.caE<gt>,
Tim Jenness E<lt>t.jenness@jach.hawaii.eduE<gt>

=head1 COPYRIGHT

Copyright (C) 2004-2007 Particle Physics and Astronomy Research
Council and University of British Columbia.  All Rights Reserved.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307,
USA

=cut


# Should I be verbose (default to no)
my $verbose = (exists $_MAKE_MOSAIC_FRAME_{VERBOSE} &&
               defined $_MAKE_MOSAIC_FRAME_{VERBOSE}) ?
               $_MAKE_MOSAIC_FRAME_{VERBOSE} : 0;

# Do we want to use makemos?
my $makemos = (exists $_MAKE_MOSAIC_FRAME_{MAKEMOS} &&
	       defined $_MAKE_MOSAIC_FRAME_{MAKEMOS}) ?
               $_MAKE_MOSAIC_FRAME_{MAKEMOS} : 0;

# Method for determining the output pixel values
my $method = (exists $_MAKE_MOSAIC_FRAME_{METHOD} &&
	      defined $_MAKE_MOSAIC_FRAME_{METHOD}) ? 
              lc($_MAKE_MOSAIC_FRAME_{METHOD}) : ""; 

# Make sure we pass in self-consistent values
if ( $makemos ) {
  $method = (exists $_MAKE_MOSAIC_FRAME_{METHOD} &&
	     defined $_MAKE_MOSAIC_FRAME_{METHOD}) ? 
             lc($_MAKE_MOSAIC_FRAME_{METHOD}) : "mean"; 
} else {
  $method = (exists $_MAKE_MOSAIC_FRAME_{METHOD} &&
	     defined $_MAKE_MOSAIC_FRAME_{METHOD}) ? 
             lc($_MAKE_MOSAIC_FRAME_{METHOD}) : "nearest"; 
}

_MAKE_MOSAIC_ USEGRP=0 MAKEMOS=$makemos METHOD=$method VERBOSE=$verbose

