#! -*-perl-*-

=head1 NAME

_REMOVE_DC_SKY_ - Removes a DC sky value

=head1 SYNOPSIS

  _REMOVE_DC_SKY_

=head1 DESCRIPTION

Subtracts a mean sky value from an uncalibrated image. An error is
generated if this primitive is run on calibrated data since it is
assumed that this step will have been done already before calibration.

This primitive is an alternative to _REMOVE_PLANE_FROM_IMAGE_.

This is a Frame operation and should be used before group operations.

=head1 External Tasks

The following external tasks are used:

=over 4

=item KAPPA

C<csub>

=back

=head1 FILES

Creates an output file with a C<_sky> extension.

=head1 KNOWN ISSUES

Assumes that this step should be done before calibration although it's
a bit late to tell the user that it should have been done at an
earlier step.

=head1 AUTHOR

Andy Gibb E<lt>agg@astro.ubc.caE<gt>

Copyright (C) 2005 the University of British Columbia.  All Rights
Reserved.


=cut

# Units for uncalibrated data
# Should be obtained from header and a check made that the data are uncalibrated
my $rawunits = "pW";

# Loop over files in the Frm object
for my $i (1..$Frm->nfiles) {

  _FIND_SKY_STATS_ FRAME=$i MODE=online
  my $sky1 = $_FIND_SKY_STATS_{RESULTS}->[0]; # retrieve average
  my $sky2 = $_FIND_SKY_STATS_{RESULTS}->[2]; # retrieve mode 

  my $sky = $sky2; # MODAL value

  # Retrieve input and output names
  my ($in, $out) = $Frm->inout("_sky", $i);
  my $args = "scalar=$sky";

  # Subtract the sky
  $Mon{kappa_mon}->obeyw("csub","in=$in out=$out $args");
  
  $sky = sprintf "%12.7f", $sky;
  orac_print "Subtracting a sky level of $sky $rawunits from $in \n";

  # Update file
  $Frm->file($i, $out);

}

orac_print "ORAC says: Sky subtraction successful\n";

